# Generated by Django 5.2.17 on 2026-09-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='certificate',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
