# Generated by Django 5.2.17 on 2026-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_alter_certificate_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sinopsis',
            field=models.TextField(blank=True),
        ),
    ]
